'use strict';
// 隔离交互草图：没有网络调用、持久化存储或正式记录写入。
const $ = id => document.getElementById(id);
const islands = {
  home: {name:'个人主岛',title:'小陌的主岛',label:'HOME / 我的起点',x:560,y:465,scope:'安顿今天，接着上次继续',subtitle:'先安顿下来，再选择今天的去向。'},
  story: {name:'故事岛',title:'故事岛',label:'STORY / 故事的发生地',x:285,y:225,scope:'人物、叙事和编剧',subtitle:'让一个故事慢慢长出来。'},
  visual: {name:'影像与 AI 创作岛',title:'影像与 AI 创作岛',label:'VISUAL / 把想法变成画面',x:882,y:260,scope:'分镜、视听语言和 AI 视觉创作',subtitle:'从一节课、一个镜头或一个问题开始。'},
  post: {name:'剪辑音动效岛',title:'剪辑音动效岛',label:'POST / 寻找画面与声音的节奏',x:856,y:685,scope:'剪辑、声音、节奏与动效',subtitle:'在画面与声音之间，找到想表达的感觉。'}
};
const state = {current:'home',overview:false,tab:'desk',plan:null,planAdopted:false,activities:{},active:null,records:[],chat:[],mode:'plan',reentry:false,reminder:'off',cue:false};
let cameraFrame=0,toastTimer=0,lastFocus=null,audioContext=null;
const active = () => state.active ? state.activities[state.active] : null;
const here = () => state.activities[state.current] || null;
const el = (tag,text,cls) => {const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;};
function button(text,fn,cls=''){const node=el('button',text,cls);node.type='button';node.addEventListener('click',fn);return node;}
function notice(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('toast').hidden=true;},4500);}
function setPanel(open){$('learningPanel').hidden=!open;$('shell').classList.toggle('panel-closed',!open);$('reopenPanel').hidden=open;}
function moveCamera(target){cancelAnimationFrame(cameraFrame);const svg=$('world'),start=svg.getAttribute('viewBox').split(/\s+/).map(Number);if(matchMedia('(prefers-reduced-motion: reduce)').matches){svg.setAttribute('viewBox',target.join(' '));return;}const began=performance.now();const frame=now=>{const t=Math.min((now-began)/750,1),p=1-(1-t)**3;svg.setAttribute('viewBox',target.map((v,i)=>start[i]+(v-start[i])*p).join(' '));if(t<1)cameraFrame=requestAnimationFrame(frame);};cameraFrame=requestAnimationFrame(frame);}
function updateIslandVisibility(){const interior=!state.overview&&state.current!=='home';$('world').classList.toggle('overview',state.overview);document.querySelector('.map-section').classList.toggle('interior',interior);document.querySelectorAll('.island').forEach(node=>{const visible=state.overview||node.dataset.island===state.current;node.classList.toggle('background-island',!visible);node.classList.toggle('selected',node.dataset.island===state.current);node.setAttribute('tabindex',visible&&!interior?'0':'-1');node.setAttribute('aria-hidden',String(!visible||interior));});$('workspace').hidden=!interior;}
function visit(id){if(!islands[id])return;state.current=id;state.overview=false;state.tab='desk';const island=islands[id];moveCamera([island.x-310,island.y-255,620,540]);$('mapEyebrow').textContent=island.label;$('mapTitle').textContent=island.title;$('mapSubtitle').textContent=island.subtitle;$('homeButton').setAttribute('aria-pressed',String(id==='home'));$('overviewButton').setAttribute('aria-pressed','false');updateIslandVisibility();render();}
function overview(){state.overview=true;moveCamera([70,-165,1060,1230]);$('mapEyebrow').textContent='WORLD / 群岛关系';$('mapTitle').textContent='从家，去不同的领域';$('mapSubtitle').textContent='先在熟悉的四座岛之间走走，以后再向远处探索。';$('homeButton').setAttribute('aria-pressed','false');$('overviewButton').setAttribute('aria-pressed','true');updateIslandVisibility();renderHome();}
function setMode(mode){state.mode=mode;document.querySelectorAll('[data-mode]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.mode===mode)));$('sendButton').textContent=mode==='plan'?'看看这次怎么安排':'聊这一段 · 演示';$('intent').placeholder=mode==='plan'?'今天有多少时间，想做什么？\n也可以先用一段示例走走看。':'说一个困惑或一点体会就好。\n不需要重新介绍自己，也不必交笔记。';$('demoParams').hidden=mode!=='plan';}
function setTime(value){$('minutes').value=value;document.querySelectorAll('[data-time]').forEach(n=>n.setAttribute('aria-pressed',String(Number(n.dataset.time)===Number(value))));}
function makePlan(){const minutes=Number($('minutes').value),buffer=Number($('buffer').value),raw=$('lessonLength').value.trim(),lesson=raw===''?null:Number(raw);if(!Number.isFinite(minutes)||minutes<10||minutes>480||!Number.isFinite(buffer)||buffer<0||buffer>=minutes){notice('请给这次留出 10–480 分钟；休息余量要小于可用时间。');return false;}if(lesson!==null&&(!Number.isFinite(lesson)||lesson<1||lesson>480)){notice('课长未知可以留空；已知课长填 1–480 分钟。');return false;}const dest=$('destination').value,course=dest==='visual'?'老白的分镜课':dest==='story'?'这次的故事学习':dest==='post'?'这次的剪辑音动效学习':'这次想推进的事';const fits=lesson!==null&&lesson<=minutes-buffer;const step=lesson===null?'先确认这节课需要多长时间':fits?'留一段完整时间，看这节课':'这节整课顺延，先处理一个小问题';const reason=lesson===null?'目前不知道真实课长，先核对它能否放进这段连续时间。':fits?`示例课长 ${lesson} 分钟，可以放进这次的时段；边看边用自己的本子记。`:`示例课长 ${lesson} 分钟，当前只有 ${minutes-buffer} 分钟活动余量。整课留到下个合适时段。`;state.planAdopted=false;state.plan={minutes,buffer,lesson,dest,course,intent:$('intent').value.trim(),step,reason,kind:lesson===null?'check':fits?'course':'prepare'};state.reentry=false;render();return true;}
function renderPlan(){const p=state.plan;$('planCard').hidden=!p||state.planAdopted;if(!p)return;$('planIntent').textContent=p.intent||'从当前选的领域开始，具体目标仍可调整。';$('planStep').textContent=p.step;$('planReason').textContent=p.reason;$('planFinish').textContent=p.kind==='course'?'可以在看完这一节、或需要暂停的位置收尾。有疑惑再回来，不要求立刻复盘。':p.kind==='prepare'?'先从自己的笔记里挑出一个问题，或找好下次要看的位置。完成这一小步就可以停。':'找到课程位置与实际时长即可，不必为了开始学习先整理全部课程。';$('planFoot').textContent=`本次示例 ${p.minutes} 分钟 · 留 ${p.buffer} 分钟休息与余量。后续练习按状态再选。`;$('routeChoice').value=p.dest;$('routeName').textContent=islands[p.dest].name;$('goButton').textContent='按这一步开始 →';$('shortenButton').disabled=p.minutes===30;}
function shorten(forActivity=false){const current=forActivity?active():null;const dest=current?.island||state.plan?.dest||state.current;if(!state.plan||state.plan.dest!==dest)$('lessonLength').value='';$('destination').value=dest;setTime(30);$('buffer').value=Math.min(Number($('buffer').value)||0,10);if(makePlan())notice('已按半小时缩小这次安排；点“按这一步开始”才采用，不会改写已发生的学习。');}
function beginPlan(){const p=state.plan;if(!p)return;const old=active();if(old&&old.island!==p.dest&&old.status==='learning')old.status='paused';const previous=state.activities[p.dest];const a={id:previous?.id||('activity-'+Date.now()),island:p.dest,title:p.course,step:p.step,reason:p.reason,status:'ready',kind:p.kind,stop:'',draft:previous?.draft||'',closeDraft:previous?.closeDraft||'',report:'paused'};state.activities[p.dest]=a;state.active=p.dest;state.reentry=false;state.cue=false;state.reminder='off';state.planAdopted=true;if($('intent').value.trim()===p.intent)$('intent').value='';visit(p.dest);setMode('chat');$('learningPanel').scrollTop=0;setPanel(true);render();notice('已开始体验这一步；这里仍是演示安排。');}
function beginDirect(){const id=state.current,old=active();if(old&&old.island!==id&&old.status==='learning')old.status='paused';if(!here()){state.activities[id]={id:'activity-'+Date.now(),island:id,title:id==='visual'?'老白的分镜课':islands[id].scope+' · 自选内容',step:id==='visual'?'接着当前课程，或聊一个困惑':'从你想探索的内容开始',reason:'不需要先制定整天计划，也不用先把所有材料登记好。',status:'ready',kind:'free',stop:'',draft:'',closeDraft:'',report:'paused'};}state.active=id;if(here().status==='closed')here().status='ready';state.reminder='off';state.cue=false;state.tab='desk';setMode('chat');render();}
function activityStatus(a){return ({ready:'准备开始',learning:'在外部学习',resting:'歇一会儿',returned:'回来继续',paused:'暂时停在这里',closed:'这块先收尾'})[a.status]||'准备开始';}
function changeStatus(status){const a=here();if(!a||state.active!==state.current)return;a.status=status;state.cue=false;if(status==='resting')state.reminder='off';if(status==='returned')state.reminder='off';render();if(status==='returned'){setMode('chat');notice('停在哪里还在。不想交流的话，可以直接继续。');}}
function renderHome(){const a=active(),latest=state.records.at(-1);$('whereLabel').textContent=state.overview?'WORLD / 仍然是同一份学习':state.reentry?'欢迎回来 · 模拟再次打开':'HOME / 接着往前走';$('whereTitle').textContent=state.overview?'看见去向，也找得到家':a&&a.status!=='closed'?'这次停在：'+islands[a.island].name:latest?'有一枚书签，等你接着打开':'今天，从一件小事开始';$('whereText').textContent=state.overview?'点岛屿进入它的学习空间。浏览地图不会更改当前活动。':a&&a.status!=='closed'?a.step:latest?latest.next:'把今天的时间和想法告诉右边的向导，或者先随意逛逛。';$('homeContinue').hidden=!(a||latest);$('homeContinue').textContent=a&&a.status!=='closed'?'回到当前这一步 →':'打开上次的书签 →';const actions=$('homeActions');actions.replaceChildren();if(a?.island==='home'&&!state.overview){$('homeContinue').hidden=true;if(a.status==='resting')actions.append(button('休息好了，继续',()=>changeStatus('returned'),'primary'));else if(a.status==='learning')actions.append(button('我回来了',()=>changeStatus('returned'),'primary'),button('先休息',()=>changeStatus('resting')));else actions.append(button('去做这一块 ↗',()=>changeStatus('learning'),'primary'),button('这块先到这里',finishFromPanel));}}
function renderPanel(){const a=active(),home=state.current==='home';$('panelEyebrow').textContent=home?'主岛 · 随手聊聊':islands[state.current].name+' · 同一位向导';$('panelTitle').textContent=state.reentry?'小陌，接着上次来':home?'小陌，先坐一会儿':'在这里，接着聊';$('panelLead').textContent=home?'说说今天的时间和想法，慢慢开始。':'课在外面看也没关系，想聊时我在这里。';$('guideNote').textContent=a?`${activityStatus(a)}。${a.status==='resting'?'休息不用交付成果，恢复以后再继续。':a.kind==='prepare'?'先把这一步做小；原先的整课仍顺延。':'先围绕眼前这一块，不急着加新任务。'}`:'先找出眼下能完成的一步。没有周月计划，也可以开始。';$('activeLink').hidden=!a||state.current===a.island;if(a){$('activeLink').replaceChildren(el('span','当前活动在 '+islands[a.island].name),el('small',a.title+' · '+activityStatus(a)));}$('contextCaption').textContent='课程来自本人自述 · 真实章节与进度待了解';$('reentryBanner').hidden=!state.reentry;$('loadDemo').hidden=!!a||!!state.plan;$('previewReminder').disabled=!a||!['learning','ready','returned'].includes(a.status);$('reminderStatus').textContent=state.reminder==='off'?'本次未启用定时提醒。':state.reminder==='later'?'这次先不打断；没有启动延后计时。':'正在预览一次窗口内提示。';$('cue').hidden=!state.cue;$('stageStatus').textContent=a?`现在：${activityStatus(a)} · 完成情况由你回来时说明`:'安排 → 去学 → 想聊时回来 → 留下接续点';}
function render(){renderHome();renderPanel();renderPlan();renderSpace();renderChat();}
function renderChat(){const log=$('chatLog');log.hidden=state.chat.length===0;log.replaceChildren(...state.chat.map(m=>{const p=el('div',undefined,'chat-message '+(m.role==='guide'?'guide':''));p.append(el('small',m.role==='guide'?'流程示意 · 未连接模型':'你的输入 · 仅本页'),el('span',m.text));return p;}));}
function renderSpace(){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===state.tab)));$('spaceBody').setAttribute('aria-labelledby',state.tab==='desk'?'deskTab':state.tab==='courses'?'coursesTab':'tracesTab');$('spaceScope').textContent='岛内空间草图 · '+islands[state.current].scope;const body=$('spaceBody');body.replaceChildren();if(state.current==='home')return;if(state.tab==='courses'){renderCourses(body);return;}if(state.tab==='traces'){renderTraces(body);return;}renderDesk(body);}
function renderDesk(body){const a=here(),isActive=a&&state.active===state.current;if(!a){const box=el('div',undefined,'empty-space');box.append(el('span','先在这里坐坐','eyebrow'),el('h3',state.current==='visual'?'分镜、镜头，从一小块开始':'这座岛，还留着很多空白'),el('p',state.current==='visual'?'你最近在学老白的分镜课。课次与进度还没告诉我，可以直接接着学，也可以只聊一个问题。':'可以在这里探索、看片，或者聊一个问题。选定材料后，它才会成为课程架上的内容。'),button(state.current==='visual'?'接着分镜课体验 →':'在这里开始一段体验 →',beginDirect,'primary'),el('p','不必先安排整天，也不必完成全部步骤。','note'));body.append(box);return;}
  const head=el('div',undefined,'desk-head'),text=el('div');text.append(el('span',activityStatus(a),'status-pill'),el('h3',a.title),el('p','课次与原课程链接待补 · 可照常在自己的课程页面学习'));const book=document.createElementNS('http://www.w3.org/2000/svg','svg');book.setAttribute('viewBox','0 0 80 92');book.setAttribute('class','book-drawing');book.setAttribute('aria-hidden','true');book.innerHTML='<path d="M14 13 65 7 69 77 19 86Z"/><path d="m21 13 5 70M43 10l1 24 7-5 7 4-1-25M31 45l25-3M33 54l20-3M34 63l12-2" fill="none"/>';head.append(text,book);body.append(head);
  const step=el('section',undefined,'next-step');step.append(el('span',a.stop?'书签停在这里':'这次先做','eyebrow'),el('h4',a.stop||a.step),el('p',a.reason));if(a.status==='resting')step.append(el('p','走走、看看窗外，或者什么也不做。回来了点一下继续即可。'));else if(a.status==='learning')step.append(el('p','可以切去看课、记纸笔笔记或创作。网页不监测其他软件，也不按停留时长判断完成。'));body.append(step);
  const actions=el('div',undefined,'step-actions');if(!isActive){actions.append(button('回到这段学习',()=>{const old=active();if(old&&old.island!==a.island&&old.status==='learning')old.status='paused';state.active=a.island;a.status='ready';a.report='paused';state.cue=false;state.reminder='off';render();},'primary'));}else if(a.status==='resting'){actions.append(button('休息好了，继续',()=>changeStatus('returned'),'primary'));}else if(a.status==='learning'){actions.append(button('我回来了',()=>changeStatus('returned'),'primary'),button('先歇一会儿',()=>changeStatus('resting')));}else if(a.status==='closed'){actions.append(button(a.lastTrace?'从书签继续':'再从这里开始',()=>{a.status='ready';a.report='paused';render();},'primary'));}else{actions.append(button(a.kind==='prepare'?'去处理这一个问题 ↗':'去学这一块 ↗',()=>changeStatus('learning'),'primary'),button('只聊一个困惑',()=>{setMode('chat');setPanel(true);$('intent').focus();}));}body.append(actions);
  if(isActive&&a.status!=='closed'){const footer=el('div',undefined,'desk-footer');footer.append(button('这块先到这里',()=>{if(!a.closing)a.closeDraft=a.draft;a.closing=true;renderSpace();$('closeNote').focus();}),button('先休息',()=>changeStatus('resting')),button('时间变少了',()=>{shorten(true);setPanel(true);$('planCard').scrollIntoView({block:'nearest'});}));body.append(footer);}
  body.append(el('p','看完课程、做过练习、真正掌握，是不同的进展。','activity-meta'));if(a.closing&&isActive)renderClose(body,a);
}
function renderCourses(body){body.append(el('span','COURSES / 课程与材料','eyebrow'),el('p','课程属于这座岛，不需要每门课建一座新岛。','note'));if(state.current==='visual'){const b=button('',()=>{if(!here())beginDirect();state.tab='desk';renderSpace();},'course-book');b.append(el('span','','book-spine'));const info=el('span');info.append(el('strong','老白的分镜课'),el('small','来源：本人在学自述 · 课次与链接待补'),el('small','打开当前学习位置 →'));b.append(info);body.append(b);}else if(here()){const b=button('',()=>{state.tab='desk';renderSpace();},'course-book');b.append(el('span','','book-spine'),el('strong',here().title));body.append(b);}else body.append(el('p','这里还没有具体课程。可以先自由探索，不需要为填满架子而加课。','empty-space'));body.append(el('p','有真实课程地址时，这里会提供入口；草图没有虚构链接或播放器。','note'));}
function renderTraces(body){body.append(el('span','MEMORIES / 在这座岛留下的','eyebrow'),el('p','每枚书签来自一次本页收尾。点开，可以找回问题和接续点。','note'));const records=state.records.filter(r=>r.island===state.current);if(!records.length){body.append(el('div','这里还没有书签。开始过、没看完、仍有疑问，都可以留下痕迹；不必等整门课结束。','empty-space'));return;}records.slice().reverse().forEach(r=>{const b=button('',()=>openTrace(r),'trace-book');b.append(el('span','','book-spine'));const text=el('span');text.append(el('span',r.time+' · 本页演示','trace-date'),el('strong',r.title),el('small',r.reportLabel),el('small',r.next));b.append(text);body.append(b);});}
const reports={paused:'暂停 · 完成情况未说明',partial:'看过一部分 · 观看自述',lesson:'本节看完 · 观看自述',course:'整门看完 · 观看自述',practice:'做过练习 · 尚未查看产物'};
function renderClose(body,a){const section=el('section',undefined,'close-entry');section.append(el('h3','停在哪里，留一句就好'),el('p','正式使用时从自然交流中归纳；这里用几个操作体验收尾。'));const label=el('label','想留下的收获、疑惑或停止处（可不填）');label.htmlFor='closeNote';const note=el('textarea');note.id='closeNote';note.placeholder='比如：这节看完了，但镜头衔接的判断还不清楚。';note.value=a.closeDraft??'';note.addEventListener('input',()=>{a.closeDraft=note.value;});const statusLabel=el('label','本次进展的说法');statusLabel.htmlFor='reportKind';const select=el('select');select.id='reportKind';Object.entries(reports).forEach(([id,text])=>{const o=el('option',text);o.value=id;select.append(o);});select.value=a.report;select.addEventListener('change',()=>{a.report=select.value;});const nextLabel=el('label','下次从这里接着（可不填）');nextLabel.htmlFor='nextPoint';const next=el('input');next.type='text';next.id='nextPoint';next.style='width:100%;border:1px solid var(--line);border-radius:8px;padding:9px;font-size:12px';next.placeholder='没有想好也没关系，下次再决定。';next.value=a.nextDraft||'';next.addEventListener('input',()=>{a.nextDraft=next.value;});const actions=el('div',undefined,'step-actions');actions.append(button('留下本页书签',()=>finish(true),'primary'),button('这次不留，先结束',()=>finish(false)));section.append(label,note,statusLabel,select,nextLabel,next,actions,button('先继续，还不收尾',()=>{a.closing=false;if(a.island==='home')closeDialog();else renderSpace();},'small-link'),el('p','仅暂存在本页，不写入正式学习历史；刷新会清空。'));body.append(section);}
function finish(keep){const a=here();if(!a||!a.closing||state.active!==a.island)return;if(a.island==='home')closeDialog();if(keep){const r={id:'trace-'+Date.now()+'-'+state.records.length,island:a.island,title:a.title,note:a.closeDraft??'',report:a.report,reportLabel:reports[a.report],next:a.nextDraft?.trim()||'继续这段学习，具体停止处下次再确认。',time:new Date().toLocaleDateString('zh-CN'),source:'来自本次手动填写的演示内容；未查看原课程、笔记或练习。'};state.records.push(r);a.stop=r.next;a.lastTrace=r.id;notice('书签已暂放在本页，可点开接续；未写入真实学习记录。');}else{a.stop='';a.lastTrace=null;notice('这次没有新增书签或接续记录。已有书签保持不变。');}a.closing=false;a.status='closed';a.report='paused';a.draft='';a.closeDraft='';a.nextDraft='';state.cue=false;state.reminder='off';state.active=null;state.tab=keep?'traces':'desk';render();if(keep&&a.island==='home')openTrace(state.records.at(-1));}
function openTrace(r){const detail=el('div',undefined,'trace-detail');detail.append(el('span','本页演示书签 · '+r.time,'source-label'),el('h3',r.title),el('p',r.reportLabel),el('p',r.note||'这次没有留下额外交流。'),el('p','下次：'+r.next),el('p',r.source,'note'),el('p','这是经历记录，未形成掌握结论。','note'),button('从这个位置继续 →',()=>{closeDialog();resumeTrace(r);},'primary'));openDialog('翻开这枚书签',[detail]);}
function resumeTrace(r){const old=active();if(old&&old.island!==r.island&&old.status==='learning')old.status='paused';state.activities[r.island]={id:'activity-'+Date.now(),island:r.island,title:r.title,step:r.next,reason:'接续来自上一枚本页书签；不会因为重新打开而认定新的进展。',stop:r.next,status:'ready',kind:'free',draft:'',closeDraft:'',report:'paused'};state.active=r.island;state.reentry=false;state.reminder='off';state.cue=false;visit(r.island);setMode('chat');render();}
function send(){const text=$('intent').value.trim();if(state.mode==='plan'){if(makePlan())notice('已展示安排逻辑。草图使用下面的演示参数，不理解文字里的时间。');return;}if(!text){notice('有想聊的内容再说，或者直接继续学习。');return;}state.chat.push({role:'user',text});if(!active()){state.active=state.current;state.activities[state.current]={id:'activity-'+Date.now(),island:state.current,title:'这一段交流',step:'围绕刚才的问题接着聊',reason:'直接从一个问题开始，不需要先制定学习计划。',status:'returned',kind:'chat',stop:'',draft:'',closeDraft:'',report:'paused'};}const a=active();a.draft+=(a.draft?'\n':'')+text;state.chat.push({role:'guide',text:'这里会接着你这一段交流：解释困惑、讨论收获或查看练习，由你的需要决定。草图暂不生成知识回答，也不会自动开始考试。'});$('intent').value='';render();$('chatLog').scrollTop=$('chatLog').scrollHeight;}
function showCue(){const a=active();if(!a||!['ready','learning','returned'].includes(a.status))return;state.cue=true;state.reminder='preview';$('cueTitle').textContent='要不要在合适的位置歇一会儿？';$('cueText').textContent='这是一次到点提示的预览。还没看完可以继续，任务会留在原处。';renderPanel();if($('soundOn').checked)chime();}
async function chime(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){notice('此浏览器不能播放提示音，窗口提示仍可使用。');return;}audioContext??=new Audio();await audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime;osc.type='sine';osc.frequency.setValueAtTime(660,t);osc.frequency.exponentialRampToValueAtTime(440,t+.25);gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.065,t+.02);gain.gain.exponentialRampToValueAtTime(.0001,t+.45);osc.connect(gain);gain.connect(audioContext.destination);osc.start(t);osc.stop(t+.5);osc.onended=()=>{osc.disconnect();gain.disconnect();};}catch{notice('提示音未能播放，窗口提示仍在。');}}
function simulateReopen(){state.cue=false;state.reminder='off';const a=active();if(a){a.status='paused';}state.reentry=true;visit('home');setMode('plan');setPanel(true);render();notice('正在模拟下次打开：只复用本页演示内容，真实刷新不会恢复。');}
function homeContinue(){const a=active();if(a){visit(a.island);setMode('chat');setPanel(true);}else if(state.records.length)openTrace(state.records.at(-1));}
function demo(){if(active()||state.records.length||$('intent').value.trim()){notice('先保留你当前的体验内容。可在“草图说明”里重置后再走默认示例。');return;}setMode('plan');setTime(90);$('buffer').value=15;$('lessonLength').value=40;$('destination').value='visual';$('intent').value='【演示输入】下午有 90 分钟，想继续分镜课。假设这节 40 分钟。';makePlan();notice('已填入明确标记的演示假设，不是你的真实课表或课程时长。');}
function paragraph(text){return el('p',text);}
function openDialog(title,nodes){lastFocus=document.activeElement;$('dialogTitle').textContent=title;$('dialogBody').replaceChildren(...nodes);$('dialogCover').hidden=false;$('shell').inert=true;document.querySelector('.topbar').inert=true;document.querySelector('.prototype-band').inert=true;$('closeDialog').focus();}
function closeDialog(){$('dialogCover').hidden=true;$('shell').inert=false;document.querySelector('.topbar').inert=false;document.querySelector('.prototype-band').inert=false;if(lastFocus?.isConnected&&!lastFocus.closest('[hidden]'))lastFocus.focus();}
function directory(){const grid=el('div',undefined,'directory');Object.entries(islands).forEach(([id,i])=>{const b=button('',()=>{closeDialog();visit(id);});b.append(el('strong',i.name),el('span',i.scope));grid.append(b);});openDialog('从这里找到各座岛',[paragraph('逛岛不会更改正在做的事，同一份交流随你一起走。'),grid,paragraph('以后由小陌决定新增领域；课程、影片、项目留在相应岛内，不自动变成新岛。')]);}
function explanation(){const strip=el('div',undefined,'step-strip');['主岛安排','进入学习桌','外部学习 / 休息','回来交流','留下书签','下次接续'].forEach(text=>strip.append(el('span',text)));openDialog('先把一次使用走通',[paragraph('四座岛各有一套原创二维景观。点书屋、练习台、放映场、长椅或小猫可以探索；故事改写、分镜排序和节奏练习可实际编辑，未虚构课程。场景仍是候选草图，最终皮肤以后再定。'),strip,paragraph('安排使用可修改的示例参数，不理解自然语言中的时间；聊天仅展示交互位置，不生成真实知识回答。轻提醒由按钮手动预览，不启用定时器；可选择试听一次轻声。'),paragraph('本页输入、活动和书签只在内存里。“模拟下次打开”复用本页内容；刷新或关闭后清空。没有模型调用、录音转写、正式保存或服务退出。'),paragraph('不想总结可以直接继续，看片和休息不要求产出。书签不代表掌握。'),button('重置本页演示',()=>{closeDialog();location.reload();})]);}
function cycle(){openDialog('拉远一点，看学习方向',[paragraph('今天只突出眼下的一步。周安排选推进重点，月安排看方向与取舍，都会允许现实情况改变。'),paragraph('当前正式资料还没有阶段主攻或待执行周月安排，所以草图不制造课程表或完成率。'),paragraph('正式接入后，会在需要时根据已有学习记录一起回看，再调整下一轮；没有长期计划也能先学一块。')]);}
function finishFromPanel(){const a=active();if(!a){notice('现在没有进行中的活动。可以直接结束，也可以点书签回访。');return;}visit(a.island);if(!a.closing)a.closeDraft=a.draft;a.closing=true;if(a.island==='home'){openDialog('主岛这段交流的收尾',[]);const body=$('dialogBody');renderClose(body,a);}else{if(typeof openPlace==='function')openPlace('desk');else renderSpace();$('closeNote').focus();}}
$('homeButton').addEventListener('click',()=>visit('home'));$('overviewButton').addEventListener('click',()=>overview());$('directoryButton').addEventListener('click',directory);$('expansionButton').addEventListener('click',directory);$('explainButton').addEventListener('click',explanation);$('collapsePanel').addEventListener('click',()=>{setPanel(false);$('reopenPanel').focus();});$('reopenPanel').addEventListener('click',()=>{setPanel(true);$('collapsePanel').focus();});
document.querySelectorAll('.island').forEach(n=>{n.addEventListener('click',()=>visit(n.dataset.island));n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();visit(n.dataset.island);}});});document.querySelectorAll('[data-tab]').forEach(n=>n.addEventListener('click',()=>{state.tab=n.dataset.tab;renderSpace();}));document.querySelectorAll('[data-mode]').forEach(n=>n.addEventListener('click',()=>setMode(n.dataset.mode)));document.querySelectorAll('[data-time]').forEach(n=>n.addEventListener('click',()=>setTime(n.dataset.time)));
$('planForm').addEventListener('submit',e=>{e.preventDefault();send();});$('planForm').addEventListener('invalid',e=>{if(e.target.closest('.demo-parameters'))$('demoParams').open=true;},true);$('goButton').addEventListener('click',()=>beginPlan());$('routeChoice').addEventListener('change',()=>{$('destination').value=$('routeChoice').value;makePlan();});$('shortenButton').addEventListener('click',()=>shorten());$('reviseButton').addEventListener('click',()=>{if(typeof window.editDaySchedule==='function'){window.editDaySchedule();$('demoParams').open=true;}else{setMode('plan');$('demoParams').open=true;$('minutes').focus();}});$('justExplore').addEventListener('click',()=>{overview();setPanel(false);notice('随意逛逛，不新增任务，也不要求学习成果。');});$('loadDemo').addEventListener('click',()=>demo());$('simulateReopen').addEventListener('click',simulateReopen);$('homeContinue').addEventListener('click',homeContinue);$('activeLink').addEventListener('click',()=>{visit(active().island);setMode('chat');});$('cycleButton').addEventListener('click',cycle);$('previewReminder').addEventListener('click',showCue);$('cancelReminder').addEventListener('click',()=>{state.cue=false;state.reminder='off';renderPanel();});$('cueRest').addEventListener('click',()=>{const a=active();if(a){a.status='resting';state.cue=false;state.reminder='off';render();}});$('cueLater').addEventListener('click',()=>{state.cue=false;state.reminder='later';renderPanel();notice('这次先继续；没有启动延后倒计时。');});$('cueCancel').addEventListener('click',()=>{state.cue=false;state.reminder='off';renderPanel();});$('wrapButton').addEventListener('click',finishFromPanel);$('closeDialog').addEventListener('click',closeDialog);$('dialogCover').addEventListener('click',e=>{if(e.target===$('dialogCover'))closeDialog();});
document.addEventListener('keydown',e=>{if($('dialogCover').hidden)return;if(e.key==='Escape')closeDialog();if(e.key==='Tab'){const nodes=[...$('dialogCover').querySelectorAll('button,[href],input,select,textarea')].filter(n=>!n.disabled&&n.getClientRects().length),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('pagehide',()=>{audioContext?.close().catch(()=>{});});
setMode('plan');updateIslandVisibility();render();
