import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { pipeline } from 'node:stream/promises';
import { transformLearningIntegration } from './adapt.mjs';

const folder=path.dirname(fileURLToPath(import.meta.url));
const projectRoot=path.resolve(folder,'../..');
const port=8790, upstreamPort=8787, stopToken=randomUUID();
const publicFiles=new Map(['index.html','app.js','bridge.js','style.css','scene.js','observatory-polish.css','observatory-polish.js','information-polish.css','information-polish.js'].map(name=>['/preview/'+name,name]));
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};
const security={ 'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; media-src 'self' blob:; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'" };
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8',...security});res.end(JSON.stringify(data));}
function getJSON(route){return new Promise((resolve,reject)=>{const request=http.get({hostname:'127.0.0.1',port:upstreamPort,path:route,agent:false,headers:{Host:`127.0.0.1:${upstreamPort}`}},response=>{let bytes=0;const chunks=[];response.on('data',chunk=>{bytes+=chunk.length;if(bytes>12*1024*1024)response.destroy(new Error('Read response too large'));else chunks.push(chunk);});response.on('error',reject);response.on('end',()=>{try{if(response.statusCode!==200)throw new Error('Formal service returned '+response.statusCode);resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')));}catch(error){reject(error);}});});request.setTimeout(5000,()=>request.destroy(new Error('Formal service not responding')));request.on('error',reject);});}
function shell(region){const labels={learning:'学习小岛',observatory:'素材观察室',information:'信息收集'};return `<header class="preview-header" aria-label="个人空间导航"><a class="preview-brand" href="/preview/"><span class="preview-mark" aria-hidden="true">⌂</span><span>小陌的个人空间<small>走走看看，再慢慢开始</small></span></a><nav class="preview-nav" aria-label="三个独立区域"><a href="/preview/">← 自由探索</a>${Object.entries(labels).map(([id,label])=>`<a href="/${id}/" data-preview-region-link="${id}"${region===id?' aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="preview-actions"><button id="previewTools" type="button" aria-expanded="true">工作栏</button><span class="preview-badge" title="浏览真实资料；保存操作请打开正式页面">界面预览</span><a id="previewFormal" href="http://127.0.0.1:8787/${region}/" target="_blank" rel="noopener">正式使用 ↗</a></div></header><div class="preview-feedback" id="previewFeedback" role="status" hidden></div>`;}
function decorateHTML(html,region){
  if(!html.includes('</head>')||!html.includes('<body>')||!html.includes('</body>'))throw new Error('Unsupported module HTML');
  const polish=['observatory','information'].includes(region)?region+'-polish':null;
  const css='<link rel="stylesheet" href="/preview/style.css">'+(polish?`<link rel="stylesheet" href="/preview/${polish}.css">`:'');
  const scripts='<script src="/preview/bridge.js" defer></script>'+(polish?`<script src="/preview/${polish}.js" defer></script>`:'');
  return html.replace('</head>',css+'</head>').replace('<body>',`<body data-preview-region="${region}">${shell(region)}`).replace('</body>',scripts+'</body>');
}
async function proxy(req,res,url){await new Promise((resolve,reject)=>{const request=http.request({hostname:'127.0.0.1',port:upstreamPort,path:url.pathname+url.search,method:req.method,agent:false,headers:{Host:`127.0.0.1:${upstreamPort}`,...(req.headers.range?{Range:req.headers.range}:{}),...(req.headers.accept?{Accept:req.headers.accept}:{})}},async response=>{try{const region=['learning','observatory','information'].find(id=>url.pathname===`/${id}/`||url.pathname===`/${id}/index.html`);const transform=!!region||url.pathname==='/learning/integration.js';const headers={...security};for(const name of ['content-type','content-disposition','accept-ranges','content-range','location'])if(response.headers[name])headers[name]=response.headers[name];if(transform&&response.statusCode===200&&req.method==='GET'){let bytes=0;const chunks=[];for await(const chunk of response){bytes+=chunk.length;if(bytes>4*1024*1024)throw new Error('Preview source too large');chunks.push(chunk);}let content=Buffer.concat(chunks).toString('utf8');content=region?decorateHTML(content,region):transformLearningIntegration(content);res.writeHead(200,headers);res.end(content);}else{res.writeHead(response.statusCode??502,headers);await pipeline(response,res);}resolve();}catch(error){reject(error);}});request.setTimeout(15000,()=>request.destroy(new Error('Preview read timed out')));request.on('error',reject);request.end();});}
const boot=await getJSON('/api/app/bootstrap');
if(boot.data?.app!=='xiaomo-personal-unified'||String(boot.data.projectRoot).toLowerCase()!==projectRoot.toLowerCase())throw new Error('8787 is not the expected formal project; preview not started.');
const server=http.createServer(async(req,res)=>{try{if(![`127.0.0.1:${port}`,`localhost:${port}`].includes(req.headers.host)){json(res,403,{ok:false,error:{code:'LOCAL_ONLY',message:'仅支持本机预览地址。'}});return;}const url=new URL(req.url,`http://127.0.0.1:${port}`);if(req.method==='POST'&&url.pathname==='/preview/api/stop'&&req.headers['x-preview-token']===stopToken){json(res,200,{ok:true,stopping:true});setTimeout(()=>server.close(),30);return;}if(!['GET','HEAD'].includes(req.method)){json(res,403,{ok:false,error:{code:'PREVIEW_READONLY',message:'这里是界面预览，未写入正式资料。请使用右上角“正式使用”。',retryable:false}});return;}if(url.pathname==='/'){res.writeHead(302,{Location:'/preview/',...security});res.end();return;}if(url.pathname==='/preview/api/health'){json(res,200,{ok:true,app:'xiaomo-exploration-preview',pid:process.pid,projectRoot,readOnly:true,port,formalPort:upstreamPort,stopToken});return;}if(url.pathname==='/preview/api/summary'){const results=await Promise.allSettled([getJSON('/api/observatory/materials'),getJSON('/information/api/state')]);const materials=results[0].status==='fulfilled'?results[0].value:null;const info=results[1].status==='fulfilled'?results[1].value:null;json(res,200,{ok:true,materials:Array.isArray(materials?.data?.records)?materials.data.records.length:null,opportunities:Array.isArray(info?.items)?info.items.length:null,source:'已保存的正式资料，只读'});return;}const staticName=url.pathname==='/preview/'?'index.html':publicFiles.get(url.pathname);if(staticName){res.writeHead(200,{'Content-Type':types[path.extname(staticName)],...security});res.end(req.method==='HEAD'?undefined:await fs.readFile(path.join(folder,'public',staticName)));return;}if(['/learning','/observatory','/information'].includes(url.pathname)){res.writeHead(302,{Location:url.pathname+'/',...security});res.end();return;}if(['/learning/','/observatory/','/information/','/api/'].some(prefix=>url.pathname.startsWith(prefix))){await proxy(req,res,url);return;}json(res,404,{ok:false,error:{code:'NOT_FOUND',message:'预览入口不存在。'}});}catch(error){if(!res.headersSent)json(res,502,{ok:false,error:{code:'PREVIEW_UNAVAILABLE',message:'预览暂未读到原模块。正式资料保留，请确认8787仍在运行。'}});else res.destroy();process.stderr.write(error.message+'\n');}});
server.listen(port,'127.0.0.1',()=>process.stdout.write(`探索预览：http://127.0.0.1:${port}/preview/ · 只读连接原8787 · PID ${process.pid}\n`));
server.on('error',error=>{process.stderr.write(error.message+'\n');process.exitCode=1;});
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close());
