import fs from 'node:fs/promises';
import fss from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash, randomUUID } from 'node:crypto';

export const PROJECT_ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');
export const DEFAULT_UI_FILE=path.join(PROJECT_ROOT,'学习小岛','data','ui-state.json');
export const UI_MAX_BYTES=128*1024;
export class UIError extends Error{constructor(code,message,status=400,retryable=false,details={}){super(message);this.code=code;this.status=status;this.retryable=retryable;this.details=details;}}
const err=(...args)=>{throw new UIError(...args);};
const stable=value=>Array.isArray(value)?'['+value.map(stable).join(',')+']':value&&typeof value==='object'?'{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+stable(value[k])).join(',')+'}':JSON.stringify(value);
const sha=value=>createHash('sha256').update(stable(value)).digest('hex');
function inside(child,parent){const r=path.relative(parent,child);return !!r&&r!=='..'&&!r.startsWith(`..${path.sep}`)&&!path.isAbsolute(r);}
async function recoverDeadLock(lock){try{const before=await fs.lstat(lock);if(!before.isFile()||before.isSymbolicLink()||before.size>4096||Date.now()-before.mtimeMs<1000)return false;const raw=await fs.readFile(lock,'utf8');const owner=JSON.parse(raw);if(!Number.isSafeInteger(owner.pid)||owner.pid<1||typeof owner.createdAt!=='string')return false;try{process.kill(owner.pid,0);return false;}catch(e){if(e.code!=='ESRCH')return false;}const after=await fs.lstat(lock);if(after.dev!==before.dev||after.ino!==before.ino||after.size!==before.size||after.mtimeMs!==before.mtimeMs||await fs.readFile(lock,'utf8')!==raw)return false;await fs.unlink(lock);return true;}catch{return false;}}
function safeJSON(value,depth=0){if(depth>15)err('INVALID_UI_STATE','界面状态嵌套过深。');if(value===null||typeof value==='boolean')return;if(typeof value==='string'){if(value.length>64000)err('INVALID_UI_STATE','单项界面文字过长。');return;}if(typeof value==='number'){if(!Number.isFinite(value))err('INVALID_UI_STATE','界面数值无效。');return;}if(Array.isArray(value)){if(value.length>1000)err('INVALID_UI_STATE','界面条目超过1000项。');for(const v of value)safeJSON(v,depth+1);return;}if(!value||typeof value!=='object'||Object.getPrototypeOf(value)!==Object.prototype)err('INVALID_UI_STATE','界面状态必须是普通JSON。');for(const [key,v]of Object.entries(value)){if(['__proto__','constructor','prototype'].includes(key)||key.length>150)err('INVALID_UI_STATE','界面字段不安全。');safeJSON(v,depth+1);}}
export function validateUIState(value){safeJSON(value);if(!value||Array.isArray(value)||value.version!==1||Object.keys(value).some(k=>!['version','islandState','lifeState','fields','panelOpen'].includes(k)))err('INVALID_UI_STATE','界面状态根字段或version不符合约定。');if(Buffer.byteLength(JSON.stringify(value),'utf8')>UI_MAX_BYTES)err('UI_STATE_TOO_LARGE','界面草稿超过128KiB，请保留必要停止处，不归档完整聊天。',413);return value;}
export class UIStateStore{
 constructor({projectRoot=PROJECT_ROOT,stateFile=DEFAULT_UI_FILE,scope='production'}={}){if(!path.isAbsolute(stateFile))err('INVALID_UI_PATH','UI数据文件必须是绝对路径。');if(scope==='production'&&path.resolve(stateFile)!==DEFAULT_UI_FILE)err('INVALID_UI_PATH','正式UI只能使用固定学习小岛数据目录。');if(scope==='isolated'&&!inside(path.resolve(stateFile),path.join(PROJECT_ROOT,'验证','三系统整合')))err('INVALID_UI_PATH','隔离UI须位于验证/三系统整合。');if(!['production','isolated'].includes(scope))err('INVALID_UI_PATH','UI运行范围无效。');this.file=path.resolve(stateFile);this.projectRoot=path.resolve(projectRoot);this.scope=scope;}
 async #safePath(){let dir=path.dirname(this.file);while(!fss.existsSync(dir))dir=path.dirname(dir);const actual=await fs.realpath(dir);if(actual.toLowerCase()!==path.resolve(dir).toLowerCase())err('INVALID_UI_PATH','UI数据目录含重定向路径，拒绝写入。',403);if(fss.existsSync(this.file)&&(await fs.lstat(this.file)).isSymbolicLink())err('INVALID_UI_PATH','UI数据文件不能是符号链接。',403);}
 identity(record){return{storeId:record.storeId,projectRoot:this.projectRoot,canonicalPath:this.file,schemaVersion:1,scope:this.scope};}
 async read(){await this.#safePath();let raw;try{raw=await fs.readFile(this.file,'utf8');}catch(e){if(e.code==='ENOENT')err('UI_STATE_MISSING','界面状态尚未初始化；读取没有创建文件。',404,false,{exists:false,initializationRequired:true});throw e;}if(Buffer.byteLength(raw)>512*1024)err('INVALID_UI_DATABASE','界面状态文件异常过大。',503);let r;try{r=JSON.parse(raw);}catch{err('INVALID_UI_DATABASE','界面状态文件损坏，保留原文件，不显示空状态。',503);}if(r.schemaVersion!==1||!/^ui_[a-f0-9-]{36}$/.test(r.storeId)||r.projectRoot!==this.projectRoot||r.scope!==this.scope||!Number.isSafeInteger(r.revision)||r.revision<1||!Array.isArray(r.submissions))err('INVALID_UI_DATABASE','界面数据身份或结构不符合当前入口。',503);validateUIState(r.state);return r;}
 async #locked(task){await this.#safePath();await fs.mkdir(path.dirname(this.file),{recursive:true});await this.#safePath();const lock=this.file+'.lock';let h;const end=Date.now()+1500;while(!h){try{h=await fs.open(lock,'wx');}catch(e){if(e.code!=='EEXIST')throw e;if(await recoverDeadLock(lock))continue;if(Date.now()>end)err('UI_STATE_BUSY','界面状态正被写入，保留草稿和提交ID后重试。',503,true);await new Promise(r=>setTimeout(r,40));}}try{await h.writeFile(JSON.stringify({pid:process.pid,createdAt:new Date().toISOString()}));await h.sync();return await task();}finally{await h.close();await fs.unlink(lock).catch(()=>{});}}
 async #save(record){const temp=this.file+'.'+randomUUID()+'.tmp';let h;try{h=await fs.open(temp,'wx');await h.writeFile(JSON.stringify(record),'utf8');await h.sync();await h.close();h=null;await fs.rename(temp,this.file);}finally{await h?.close();await fs.unlink(temp).catch(()=>{});}const check=await this.read();if(sha(check)!==sha(record))err('UI_WRITE_UNVERIFIED','界面写入后的回读不一致，保留提交ID核对。',500);return check;}
 async initialize(state){validateUIState(state);return this.#locked(async()=>{if(fss.existsSync(this.file))err('UI_STATE_EXISTS','界面状态已存在，初始化不覆盖；重新读取。',409);const r={schemaVersion:1,storeId:'ui_'+randomUUID(),projectRoot:this.projectRoot,scope:this.scope,revision:1,state,submissions:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await this.#save(r);return{identity:this.identity(r),revision:r.revision,state:r.state,verification:{persisted:true,snapshotVerified:true}};});}
 async write(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['identity','expectedRevision','submissionId','state'].includes(k)))err('INVALID_UI_STATE','界面提交字段不正确。');validateUIState(input.state);if(typeof input.submissionId!=='string'||!/^[A-Za-z0-9_-]{8,128}$/.test(input.submissionId)||!Number.isSafeInteger(input.expectedRevision)||input.expectedRevision<1)err('INVALID_UI_STATE','提交ID或expectedRevision无效。');return this.#locked(async()=>{const r=await this.read();if(sha(input.identity)!==sha(this.identity(r)))err('UI_IDENTITY_MISMATCH','界面数据身份变化，停止保存。',409);const digest=sha(input);const old=r.submissions.find(s=>s.submissionId===input.submissionId);if(old){if(old.payloadSha256!==digest)err('UI_SUBMISSION_CONFLICT','同提交ID已用于不同界面内容。',409);return{identity:this.identity(r),revision:r.revision,state:r.state,receipt:old,verification:{persisted:true,snapshotVerified:true,currentRevision:r.revision,currentMatchesSubmittedRevision:r.revision===old.revision}};}if(r.revision!==input.expectedRevision)err('UI_REVISION_CONFLICT','另一页面或会话已更新界面，保留当前草稿并重读合并。',409,false,{expectedRevision:input.expectedRevision,actualRevision:r.revision});const receipt={submissionId:input.submissionId,payloadSha256:digest,revision:r.revision+1,savedAt:new Date().toISOString(),stateSha256:sha(input.state)};r.revision++;r.state=input.state;r.updatedAt=receipt.savedAt;r.submissions=[...r.submissions.slice(-99),receipt];await this.#save(r);return{identity:this.identity(r),revision:r.revision,state:r.state,receipt,verification:{persisted:true,snapshotVerified:true,currentRevision:r.revision,currentMatchesSubmittedRevision:true}};});}
}
