import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { initStore, PROJECT_ROOT, ObservatoryStore } from '../../../../web/observatory/store.mjs';

const testsRoot=path.dirname(fileURLToPath(import.meta.url));
const runRoot=path.join(testsRoot,`integration-${new Date().toISOString().replace(/[:.]/g,'-')}`);
const dataDir=path.join(runRoot,'isolated','data');fs.mkdirSync(runRoot,{recursive:true});
const cliPath=path.join(PROJECT_ROOT,'web','observatory','cli.mjs');
const results=[];let server;let base;let token;let identity;let material;let topic;let stagePayload;
const sid=()=>randomUUID();
// Research evidence is derived at read time; compare immutable stored fields
// independently, and assert the derived capability contract in its own scenario.
function storedMaterial(record){const copy=structuredClone(record);delete copy.researchEvidence;delete copy.capabilities.researchStageCount;delete copy.capabilities.readScopeSummary;delete copy.capabilities.meaning;copy.capabilities.read='not_read';copy.capabilities.researched=false;return copy;}
async function test(name,fn){try{await fn();results.push({name,status:'passed'});process.stdout.write(`PASS ${name}\n`);}catch(e){results.push({name,status:'failed',error:e.stack});process.stdout.write(`FAIL ${name}: ${e.message}\n`);}}
function cli(command,args=[],payload){const file=path.join(runRoot,`input-${sid()}.json`);if(payload)fs.writeFileSync(file,JSON.stringify(payload),'utf8');const result=spawnSync(process.execPath,[cliPath,command,...args,'--data-dir',dataDir,...(payload?['--file',file]:[])],{cwd:os.tmpdir(),encoding:'utf8',windowsHide:true});const raw=result.status===0?result.stdout:result.stderr;let body;try{body=JSON.parse(raw);}catch{throw new Error(`CLI returned ${result.status}: ${raw}`);}return {...result,body};}
function startServer(dir=dataDir,mode='isolated'){
  const code=`import {createLearningServer} from ${JSON.stringify(pathToFileURL(path.join(PROJECT_ROOT,'web','server.mjs')).href)};const s=createLearningServer();s.listen(0,'127.0.0.1',()=>process.stdout.write(JSON.stringify({port:s.address().port})+'\\n'));process.on('SIGTERM',()=>s.close(()=>process.exit()));`;
  const child=spawn(process.execPath,['--input-type=module','-e',code],{cwd:os.tmpdir(),env:{...process.env,OBSERVATORY_MODE:mode,OBSERVATORY_DATA_DIR:dir},windowsHide:true,stdio:['pipe','pipe','pipe']});
  return new Promise((resolve,reject)=>{let out='';let error='';child.stderr.on('data',c=>error+=c);child.stdout.on('data',c=>{out+=c;try{const ready=JSON.parse(out.trim());resolve({child,base:`http://127.0.0.1:${ready.port}`,error:()=>error});}catch{}});child.once('error',reject);child.once('exit',code=>{if(!out)reject(new Error(`server failed ${code}: ${error}`));});});
}
async function stopServer(){if(server){server.child.kill();await new Promise(r=>server.child.once('exit',r));server=null;}}
async function request(route,{method='GET',body,headers={}}={}){const response=await fetch(`${base}/api/observatory/${route}`,{method,headers:{...(method==='POST'?{'Content-Type':'application/json','X-Observatory-Token':token}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:response.status,body:await response.json()};}
async function action(name,input){return request('action',{method:'POST',body:{action:name,input}});}
try{
await test('显式磁盘隔离库，不初始化或读取真实用户数据库',async()=>{identity=await initStore({dataDir,scope:'isolated'});assert.equal(identity.scope,'isolated');assert.equal(fs.existsSync(path.join(dataDir,'observatory.sqlite3')),true);});
await test('独立HTTP进程与独立CLI进程读取同一磁盘storeId/path',async()=>{server=await startServer();base=server.base;const bootstrap=await request('bootstrap');assert.equal(bootstrap.status,200,JSON.stringify(bootstrap.body));token=bootstrap.body.data.token;assert.deepEqual(bootstrap.body.data.identity,identity);assert.deepEqual(cli('identity').body.data,identity);});
await test('网页HTTP仅一个链接保存成功，无专题或研究调用',async()=>{const saved=await action('create-material',{identity,submissionId:sid(),material:{original:{kind:'link',url:'https://example.com/isolated-material'},originalImpression:'【隔离测试】停顿让我想到等待，<script>不会执行</script>'}});assert.equal(saved.status,200,JSON.stringify(saved.body));material=saved.body.data.receipt.snapshot;assert.equal(material.title,'');assert.equal(material.tags.length,0);assert.equal((await request('topics')).body.data.records.length,0);const independent=cli('read-material',[material.materialId]);assert.equal(independent.status,0);assert.deepEqual(storedMaterial(independent.body.data.record),material);});
await test('同submissionId同内容返回同收据，不同内容拒绝',async()=>{const input={identity,submissionId:sid(),material:{original:{kind:'text',text:'【隔离文本】只收藏，不研究'}}};const a=await action('create-material',input);const b=cli('create-material',[],input);assert.deepEqual(a.body.data.receipt,b.body.data.receipt);const c=await action('create-material',{...input,material:{original:{kind:'text',text:'不同正文'}}});assert.equal(c.status,409);assert.equal(c.body.error.code,'SUBMISSION_ID_CONFLICT');});
await test('网页新版本与CLI旧版本冲突，原话修正有历史',async()=>{const patch={identity,submissionId:sid(),materialId:material.materialId,expectedRevision:material.revision,actor:'user',patch:{title:'【隔离】等待的停顿',tags:['光影','用途：氛围'],currentImpression:'【隔离】更准确：被慢下来吸引',addNote:'备注关键词静静等候',source:{title:'测试来源补充',uri:'https://example.com/isolated-material',locator:'用户描述'}}};const saved=await action('update-material',patch);assert.equal(saved.status,200);const stale=cli('update-material',[],{...patch,submissionId:sid(),patch:{title:'旧版不应覆盖'}});assert.equal(stale.status,4);assert.equal(stale.body.error.code,'REVISION_CONFLICT');material=saved.body.data.receipt.snapshot;assert.equal(material.originalImpression.includes('停顿'),true);assert.equal(material.impressionHistory[0].before.includes('停顿'),true);assert.equal(material.original.source,undefined);assert.equal(material.sourceHistory.length,1);});
await test('AIactor不改用户原话，未支持补丁整体拒绝',async()=>{const saved=await action('update-material',{identity,submissionId:sid(),materialId:material.materialId,expectedRevision:material.revision,actor:'ai',patch:{currentImpression:'改写'}});assert.equal(saved.status,403);assert.equal(saved.body.error.code,'AUTHORSHIP_PROTECTED');assert.deepEqual(storedMaterial((await request(`materials/${material.materialId}`)).body.data.record),material);});
await test('交接由磁盘生成并携带真实ID版本与读取命令',async()=>{const h=await request(`handoff?kind=material&id=${material.materialId}`);assert.equal(h.status,200);assert.equal(h.body.data.identity.storeId,identity.storeId);assert.equal(h.body.data.currentRevision,material.revision);assert.equal(h.body.data.text.includes(dataDir),true);assert.equal(h.body.data.text.includes('研究入口.md'),true);fs.writeFileSync(path.join(runRoot,'material-handoff.json'),JSON.stringify(h.body.data,null,2));});
await test('CLI创建专题、写阶段完整正文，HTTP回读ID版本和段落来源',async()=>{const created=cli('create-topic',[],{identity,submissionId:sid(),topic:{title:'【隔离】停顿为何有等待感',question:'停顿与等待感的关系',scope:'仅这条用户描述，不声称看过原片',materialIds:[material.materialId]}});assert.equal(created.status,0);topic=created.body.data.receipt.snapshot;stagePayload={identity,submissionId:sid(),topicId:topic.topicId,expectedRevision:topic.revision,materialVersions:[{materialId:material.materialId,revision:material.revision}],stage:{focus:'【隔离】等待的停顿',confirmed:['已保存原话，但链接并未访问'],candidates:['以后核对原片时长'],unknown:['镜头真实长度未知'],nextStep:'取得可读取原件后，只核对停顿时长',paragraphs:[{heading:'观察边界',markdown:'【隔离测试正文】用户描述和原话保留。尚未读取原片，不能将其当作连续声画证据。',basisKind:'user_impression',sourceRefs:[{sourceId:'s1',locator:'material.currentImpression',note:'支持用户被慢下来吸引的自述'}]}],sources:[{sourceId:'s1',kind:'material',materialId:material.materialId,locator:'currentImpression',verificationScope:'已读取持久化用户描述；未访问链接'}],limitations:['本项为技术验收；不是外部来源研究'],researchStatus:'paused'}};const written=cli('submit-stage',[],stagePayload);assert.equal(written.status,0);assert.equal(written.body.data.verification.snapshotVerified,true);topic=written.body.data.receipt.snapshot;assert.deepEqual((await request(`topics/${topic.topicId}`)).body.data.record,topic);const repeated=await action('submit-stage',stagePayload);assert.deepEqual(repeated.body.data.receipt,written.body.data.receipt);assert.equal(topic.stages.length,1);});
await test('标题标签来源原话备注及研究正文能找回素材',async()=>{for(const query of ['光影','静静等候','测试来源补充','连续声画证据']){const found=await request(`materials?status=all&query=${encodeURIComponent(query)}`);assert.equal(found.body.data.records.some(m=>m.materialId===material.materialId),true,query);}});
await test('读取与研究状态由真实阶段来源派生，未访问链接不升级全文已读',async()=>{const found=(await request(`materials/${material.materialId}`)).body.data.record;assert.equal(found.capabilities.researched,true);assert.equal(found.capabilities.researchStageCount,1);assert.equal(found.capabilities.read,'scope_documented');assert.equal(found.capabilities.readScopeSummary[0].verificationScope,'已读取持久化用户描述；未访问链接');assert.equal(found.researchEvidence[0].hasReport,true);assert.equal(found.researchEvidence[0].basedOnMaterialRevision,material.revision);assert.equal(found.capabilities.access,'not_checked');assert.equal(found.original.url,material.original.url);});
await test('一个素材多个专题；删除与恢复专题不改素材或另专题',async()=>{const second=cli('create-topic',[],{identity,submissionId:sid(),topic:{title:'【隔离】第二专题',materialIds:[material.materialId]}}).body.data.receipt.snapshot;const deleted=await action('update-topic',{identity,submissionId:sid(),topicId:topic.topicId,expectedRevision:topic.revision,patch:{status:'deleted'}});assert.equal(deleted.status,200);assert.deepEqual(storedMaterial((await request(`materials/${material.materialId}`)).body.data.record),material);assert.equal(cli('read-topic',[second.topicId]).body.data.record.materialIds[0],material.materialId);const restored=await action('update-topic',{identity,submissionId:sid(),topicId:topic.topicId,expectedRevision:deleted.body.data.receipt.revision,patch:{status:'paused'}});assert.equal(restored.status,200);topic=restored.body.data.receipt.snapshot;});
await test('错误数据路径不建空库，身份不匹配明确失败',async()=>{const missing=path.join(runRoot,'mistake','data');const bad=await startServer(missing);const originalBase=base;try{base=bad.base;const r=await request('identity');assert.equal(r.status,503);assert.equal(r.body.error.code,'DATABASE_MISSING');assert.equal(fs.existsSync(missing),false);}finally{base=originalBase;bad.child.kill();}const r=await action('create-material',{identity:{...identity,storeId:'wrong'},submissionId:sid(),material:{original:{kind:'text',text:'不应保存'}}});assert.equal(r.status,409);assert.equal(r.body.error.code,'STORE_IDENTITY_MISMATCH');});
await test('Host/Origin/token限制，URL注入与路径越界明确拒绝',async()=>{const denied=await fetch(`${base}/api/observatory/identity`,{headers:{Origin:'https://external.example'}});assert.equal(denied.status,403);const noToken=await fetch(`${base}/api/observatory/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(noToken.status,403);const unsafe=await action('create-material',{identity,submissionId:sid(),material:{original:{kind:'link',url:'javascript:alert(1)'}}});assert.equal(unsafe.status,400);assert.equal(unsafe.body.error.code,'UNSAFE_URI');});
await test('真实独立进程EXCLUSIVE锁等待失败返回busy，可相同提交恢复',async()=>{const code=`import {DatabaseSync} from 'node:sqlite';const db=new DatabaseSync(${JSON.stringify(identity.canonicalDbPath)});db.exec('BEGIN EXCLUSIVE');process.stdout.write('locked\\n');process.stdin.once('data',()=>{db.exec('ROLLBACK');db.close();process.exit()});`;const lock=spawn(process.execPath,['--input-type=module','-e',code],{windowsHide:true,stdio:['pipe','pipe','pipe']});await new Promise((resolve,reject)=>{lock.stdout.once('data',resolve);lock.once('error',reject);});const input={identity,submissionId:sid(),materialId:material.materialId,expectedRevision:material.revision,actor:'user',patch:{addNote:'锁后恢复关键词'}};try{const busy=await action('update-material',input);assert.equal(busy.status,503,JSON.stringify(busy.body));assert.equal(busy.body.error.code,'DATABASE_BUSY');assert.equal(busy.body.error.retryable,true);const childCli=cli('read-material',[material.materialId]);assert.equal(childCli.status,5);assert.equal(childCli.body.error.code,'DATABASE_BUSY');}finally{lock.stdin.write('release');await new Promise(r=>lock.once('exit',r));}const after=await action('update-material',input);assert.equal(after.status,200);material=after.body.data.receipt.snapshot;assert.equal(material.notes.at(-1).text,'锁后恢复关键词');});
await test('刷新与真实服务重启后CLI成果和用户原话仍存在',async()=>{assert.equal((await request(`topics/${topic.topicId}`)).body.data.record.revision,topic.revision);await stopServer();server=await startServer();base=server.base;const boot=await request('bootstrap');token=boot.body.data.token;assert.deepEqual(boot.body.data.identity,identity);assert.deepEqual(storedMaterial((await request(`materials/${material.materialId}`)).body.data.record),material);assert.deepEqual((await request(`topics/${topic.topicId}`)).body.data.record,topic);});
await test('独立进程可凭阶段记录接续（不冒充真实新聊天验收）',async()=>{const loaded=cli('handoff-topic',[topic.topicId]);assert.equal(loaded.status,0);assert.equal(loaded.body.data.latestStageId,topic.stages[0].stageId);assert.equal(loaded.body.data.text.includes('取得可读取原件后'),true);assert.equal(loaded.body.data.submissionTemplate.expectedRevision,topic.revision);fs.writeFileSync(path.join(runRoot,'topic-handoff.json'),JSON.stringify(loaded.body.data,null,2));});
} finally {await stopServer();fs.writeFileSync(path.join(testsRoot,'integration-evidence.json'),JSON.stringify({node:process.version,runRoot,dataDir,identity,materialId:material?.materialId,topicId:topic?.topicId,results,newChatVerification:'not_tested; independent CLI is not a new chat'},null,2));}
process.stdout.write(`${results.filter(r=>r.status==='passed').length} passed, ${results.filter(r=>r.status==='failed').length} failed\n`);if(results.some(r=>r.status==='failed'))process.exitCode=1;
