import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createLearningServer} from '../../web/server.mjs';
import {UIStateStore} from '../../web/unified/ui-state.mjs';
import {createInformationManager} from '../../web/unified/information.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..');const testRoot=path.join(root,'验证','三系统整合');const runRoot=path.join(testRoot,'host-'+new Date().toISOString().replace(/[:.]/g,'-'));fs.mkdirSync(runRoot,{recursive:true});const infoRoot=path.join(runRoot,'information');const uiFile=path.join(runRoot,'learning','data','ui-state.json');const results=[];let app;let origin;let bootstrap;let ui;let external;let lifecycleChild;
const state={version:1,islandState:{current:'learn',activities:[],records:[],chat:[],composerDrafts:{}},lifeState:{drafts:{}},fields:{intent:'【隔离测试】从这里继续',pendingChatRequest:null},panelOpen:false};
async function test(name,fn){try{await fn();results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){results.push({name,status:'failed',error:e.stack});console.log('FAIL '+name+': '+e.message);}}
async function port(){const s=http.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
async function close(s){if(s?.listening){s.closeAllConnections?.();await new Promise(r=>s.close(r));}}
async function get(route,options={}){const r=await fetch(origin+route,options);return{status:r.status,body:await r.json()};}
async function save(body,init=false){return get('/api/learning/ui-state'+(init?'/init':''),{method:'POST',headers:{'Content-Type':'application/json','X-Learning-Token':ui.token},body:JSON.stringify(body)});}
const infoPort=await port();
try{
await test('新HTTP宿主构造不启动信息、不改用户库；根与旧index转新学习页面',async()=>{app=createLearningServer({env:{LEARNING_UI_MODE:'isolated',LEARNING_UI_STATE_PATH:uiFile},informationOptions:{root:infoRoot,port:infoPort,scope:'isolated'}});await new Promise(r=>app.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+app.address().port;assert.equal(app.informationStatus().status,'not_started');for(const p of ['/','/index.html']){const r=await fetch(origin+p,{redirect:'manual'});assert.equal(r.status,302);assert.equal(r.headers.get('location'),'/learning/');}assert.equal(fs.existsSync(uiFile),false);});
await test('首次GET明确缺失，不悄悄造UI文件；缺token拒绝写',async()=>{const r=await get('/api/learning/ui-state');assert.equal(r.status,404);assert.equal(r.body.error.code,'UI_STATE_MISSING');assert.equal(r.body.error.details.exists,false);ui={token:r.body.error.details.token};assert.equal(fs.existsSync(uiFile),false);const rejected=await get('/api/learning/ui-state/init',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state})});assert.equal(rejected.status,403);});
await test('显式初始化、CAS旧版本拒绝、重复提交去重、不同payload拒绝',async()=>{const initialized=await save({state},true);assert.equal(initialized.status,200,JSON.stringify(initialized));ui=initialized.body.data;const payload={identity:ui.identity,expectedRevision:1,submissionId:'ui-test-'+randomUUID(),state:{...state,fields:{intent:'新的草稿'}}};const a=await save(payload);assert.equal(a.status,200);const b=await save(payload);assert.deepEqual(a.body.data.receipt,b.body.data.receipt);const changed=await save({...payload,state:{...state,fields:{intent:'不同内容'}}});assert.equal(changed.status,409);const stale=await save({...payload,submissionId:'ui-test-'+randomUUID()});assert.equal(stale.status,409);assert.equal(stale.body.error.code,'UI_REVISION_CONFLICT');ui=a.body.data;});
await test('真实子进程持活锁被拒绝；kill后核对死PID恢复写入',async()=>{const lock=uiFile+'.lock';const code=`import fs from 'node:fs';fs.writeFileSync(${JSON.stringify(lock)},JSON.stringify({pid:process.pid,createdAt:new Date().toISOString()}),{flag:'wx'});process.stdout.write('locked\\n');setInterval(()=>{},1000);`;const child=spawn(process.execPath,['--input-type=module','-e',code],{windowsHide:true,stdio:['ignore','pipe','pipe']});await new Promise(r=>child.stdout.once('data',r));const payload={identity:ui.identity,expectedRevision:ui.revision,submissionId:'ui-lock-'+randomUUID(),state:{...state,fields:{intent:'重启后草稿'}}};try{const busy=await save(payload);assert.equal(busy.status,503);assert.equal(busy.body.error.code,'UI_STATE_BUSY');assert.equal(busy.body.error.retryable,true);}finally{child.kill();await new Promise(r=>child.once('exit',r));}const restored=await save(payload);assert.equal(restored.status,200,JSON.stringify(restored));ui=restored.body.data;assert.equal(fs.existsSync(lock),false);});
await test('刷新/新Store实例读取同UI；普通草稿不是Markdown学习进展',async()=>{const loaded=(await get('/api/learning/ui-state')).body.data;assert.equal(loaded.revision,ui.revision);assert.equal(loaded.state.fields.intent,'重启后草稿');const independent=await new UIStateStore({stateFile:uiFile,scope:'isolated'}).read();assert.deepEqual(independent.state,ui.state);assert.equal(fs.existsSync(path.join(runRoot,'运行记录')),false);});
await test('信息缺库与未知端口拒绝，不新建空库或代理任意URL',async()=>{const missing=await get('/information/api/health');assert.equal(missing.status,503);assert.equal(missing.body.error.code,'INFORMATION_DATABASE_MISSING');assert.equal(fs.existsSync(path.join(infoRoot,'data')),false);await fsp.mkdir(path.join(infoRoot,'config'),{recursive:true});await fsp.cp(path.join(root,'信息收集','config'),path.join(infoRoot,'config'),{recursive:true});await fsp.cp(path.join(root,'信息收集','static'),path.join(infoRoot,'static'),{recursive:true});const fixture=`import sys;sys.path.insert(0,${JSON.stringify(path.join(root,'信息收集'))});from opportunities.storage import Store;from opportunities.model import empty_document;s=Store(${JSON.stringify(infoRoot)},seed=False);d=empty_document(s.source_config[0]['id'],'隔离统一测试机会','测试平台','https://example.com/isolated-unified');d['summary']='仅用于隔离验收，不是真实比赛';s.upsert(d,'isolated_fixture')`;const p=spawnSync('python',['-X','utf8','-c',fixture],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);const fake=http.createServer((q,s)=>{s.setHeader('Content-Type','application/json');s.end(JSON.stringify({app:'unknown',marker:'wrong',local_only:true}));});await new Promise(r=>fake.listen(infoPort,'127.0.0.1',r));try{const bad=await get('/information/api/health');assert.equal(bad.status,409);assert.equal(bad.body.error.code,'INFORMATION_IDENTITY_MISMATCH');await assert.rejects(()=>app.startInformation(),e=>e.code==='INFORMATION_IDENTITY_MISMATCH');}finally{await close(fake);}});
await test('自动owned启动使用原信息schema身份、固定代理同库、token与Origin边界',async()=>{const started=await app.startInformation();assert.equal(started.ownership,'owned');const health=await get('/information/api/health');assert.equal(health.body.marker,started.marker);const boot=await get('/information/api/state');assert.equal(boot.status,200);assert.equal(boot.body.items.length,1);assert.equal(boot.body.items[0].title,'隔离统一测试机会');assert.equal(boot.body.runs.length,0);bootstrap=boot.body;const bad=await get('/information/api/preference',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify({id:bootstrap.items[0].id,note:'无token不能写'})});assert.equal(bad.status,403);const good=await get('/information/api/preference',{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':bootstrap.token,Origin:origin},body:JSON.stringify({id:bootstrap.items[0].id,note:'隔离同源代理备注'})});assert.equal(good.status,200);const direct=await fetch('http://127.0.0.1:'+infoPort+'/api/state').then(r=>r.json());assert.equal(direct.items[0].note,'隔离同源代理备注');const exported=await get('/information/api/export');assert.equal(exported.body.documents.length,1);});
await test('应用stop只回收自身owned Python，已有已识别服务复用不误停',async()=>{const ownedPid=app.informationStatus().pid;const stopped=await app.stopOwnedInformation();assert.equal(stopped.stopped,true);assert.throws(()=>process.kill(ownedPid,0),e=>e.code==='ESRCH');external=createInformationManager({root:infoRoot,port:infoPort,scope:'isolated'});await external.ensureStarted();const reused=await app.startInformation();assert.equal(reused.ownership,'reused');assert.equal((await app.stopOwnedInformation()).stopped,false);assert.equal((await external.verify()).status,'ready');});
await test('学习状态服务重启仍可读取，模块切换不会丢草稿',async()=>{await close(app);app=createLearningServer({env:{LEARNING_UI_MODE:'isolated',LEARNING_UI_STATE_PATH:uiFile},informationOptions:{root:infoRoot,port:infoPort,scope:'isolated'}});await new Promise(r=>app.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+app.address().port;const loaded=await get('/api/learning/ui-state');assert.equal(loaded.body.data.identity.storeId,ui.identity.storeId);assert.equal(loaded.body.data.state.fields.intent,'重启后草稿');});
await test('Windows停止脚本真实回收owned Node/Python，不只server.close模拟',async()=>{await external.stopOwned();external=null;const nodePort=await port();const code=`import {createLearningServer} from ${JSON.stringify(pathToFileURL(path.join(root,'web','server.mjs')).href)};const s=createLearningServer({env:{LEARNING_UI_MODE:'isolated',LEARNING_UI_STATE_PATH:${JSON.stringify(uiFile)}},informationOptions:{root:${JSON.stringify(infoRoot)},port:${infoPort},scope:'isolated'}});s.listen(${nodePort},'127.0.0.1',async()=>{const r=await s.startInformation();process.stdout.write(JSON.stringify(r)+'\\n')});`;const launcher=path.join(runRoot,'server.mjs');fs.writeFileSync(launcher,code);lifecycleChild=spawn(process.execPath,[launcher],{windowsHide:true,stdio:['ignore','pipe','pipe']});let out='';const started=await new Promise((resolve,reject)=>{lifecycleChild.stdout.on('data',c=>{out+=c;try{resolve(JSON.parse(out.trim()));}catch{}});lifecycleChild.once('exit',code=>reject(new Error('lifecycle exited '+code)));});const stopPath=path.join(root,'web','Stop-LearningTerminal.ps1');const text=fs.readFileSync(stopPath,'utf8').replace("$serverPath = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) 'server.mjs'",'$serverPath = '+"'"+launcher.replaceAll("'","''")+"'").replace("$projectPath = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)",'$projectPath = '+"'"+root.replaceAll("'","''")+"'").replace("$workerPath = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) 'unified\\information-worker.py'",'$workerPath = '+"'"+path.join(root,'web','unified','information-worker.py').replaceAll("'","''")+"'");const isolatedStop=path.join(runRoot,'Stop-Isolated.ps1');fs.writeFileSync(isolatedStop,text,'utf8');const command=spawnSync('pwsh',['-NoProfile','-File',isolatedStop,'-Port',String(nodePort)],{encoding:'utf8',windowsHide:true,timeout:20000});assert.equal(command.status,0,command.stderr);assert.throws(()=>process.kill(started.pid,0),e=>e.code==='ESRCH');await new Promise(r=>setTimeout(r,100));assert.equal(lifecycleChild.exitCode,0);lifecycleChild=null;});
}finally{await app?.stopOwnedInformation().catch(()=>{});await external?.stopOwned().catch(()=>{});await close(app);lifecycleChild?.kill();fs.writeFileSync(path.join(testRoot,'backend-evidence.json'),JSON.stringify({node:process.version,runRoot,infoRoot,uiFile,infoPort,tests:results,note:'All opportunities are synthetic; no user database or learning records used as test fixtures.'},null,2));}
console.log(results.filter(r=>r.status==='passed').length+' passed, '+results.filter(r=>r.status==='failed').length+' failed');if(results.some(r=>r.status==='failed'))process.exitCode=1;
