import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { randomUUID } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { ContentStore } from './store.mjs';
import { createContentHandler } from './http.mjs';

const run=promisify(execFile),watchFile='运行记录/观影记录.md';
const oldWatch='# 观影记录\n\n| 编号 | 作品与类型 | 本人报告的观看范围 | 可选感受与不确定处 | 最近依据 |\n| W001 | 《第一部》 | 看过，是否看完未明确 | 未交流 | 2026-09-30 自述 |\n| W002 | 第二部，正式片名待核实 | 看过，是否看完未明确 | 保留未知 | 2026-09-30 自述 |\n| W003 | 动漫 | 第一、第二季均已看完 | 其他未知 | 2026-09-30 自述 |\n| W004 | 短片集 | 第一、第二季均已看完 | 未交流 | 2026-09-30 自述 |\n\n原有说明逐字保留。\n';
async function fixture(t,{watch=true}={}){const root=await fs.mkdtemp(path.join(os.tmpdir(),'xiaomo-content-'));t.after(async()=>{await fs.rm(root,{recursive:true,force:true});});if(watch){await fs.mkdir(path.join(root,'运行记录'),{recursive:true});await fs.writeFile(path.join(root,watchFile),oldWatch);}return {root,store:new ContentStore({projectRoot:root,scope:'isolated'})};}
async function payload(store,item,extra={}){const {identity,revision}=await store.bootstrap();return {identity,expectedRevision:revision,submissionId:'save_'+randomUUID(),item,...extra};}
const creation=(title='点子',body='原话')=>({kind:'creation',title,body,date:null});
const watch=()=>({kind:'watch',title:'只知道片名',body:'',date:null,watch:{status:'unknown',progress:''}});
async function tree(root){const result={};for(const name of await fs.readdir(root)){const file=path.join(root,name),stat=await fs.lstat(file);if(stat.isDirectory()){const children=await tree(file);for(const [key,value]of Object.entries(children))result[name+'/'+key]=value;}else result[name]={bytes:await fs.readFile(file,'utf8'),mtime:stat.mtimeMs};}return result;}

test('GET does not initialize absent files; original W records retain unknown dates and scoped status',async t=>{const {root,store}=await fixture(t);const before=await tree(root),data=await store.bootstrap();assert.equal(data.items.length,4);assert.equal(data.items[0].date,null);assert.equal(data.items[0].watch.status,'unknown');assert.equal(data.items[2].watch.status,'watched');await store.list({kind:'watch'});await store.detail('W001');assert.deepEqual(await tree(root),before);});
test('empty root reads without any writes',async t=>{const {root,store}=await fixture(t,{watch:false});assert.deepEqual((await store.bootstrap()).items,[]);assert.deepEqual(await fs.readdir(root),[]);});
test('title-only watch appends to original authority, duplicate retries do not append or allocate new ID',async t=>{const {root,store}=await fixture(t);const request=await payload(store,watch()),first=await store.save(request);assert.equal(first.item.id,'W005');assert.equal(first.item.date,null);assert.equal(first.item.watch.status,'unknown');const raw=await fs.readFile(path.join(root,watchFile),'utf8');assert.ok(raw.startsWith(oldWatch));assert.match(raw,/观看日期：未知/);assert.equal((await store.save(request)).duplicate,true);assert.equal(await fs.readFile(path.join(root,watchFile),'utf8'),raw);await assert.rejects(store.save({...request,item:{...request.item,title:'不同内容'}}),e=>e.code==='CONTENT_SUBMISSION_CONFLICT');});
test('watch updates and rewatch keep same ID, retain table, histories and exact whitespace',async t=>{const {root,store}=await fixture(t);const saved=await store.save(await payload(store,{...watch(),id:'W001',title:'《第一部》',body:'  补充原话\n尾部  ',date:'2026-10-05',watch:{status:'watched',progress:'看完'}}));assert.equal(saved.item.history.length,2);assert.ok(saved.item.body.endsWith('  补充原话\n尾部  '));const replay=await store.save(await payload(store,{...watch(),id:'W001',title:'《第一部》',body:'再看感受'},{action:'rewatch'}));assert.equal(replay.item.id,'W001');assert.equal(replay.item.date,null);assert.equal(replay.item.watch.status,'unknown');assert.equal(replay.item.createdAt,null);assert.equal(replay.item.history.length,3);const raw=await fs.readFile(path.join(root,watchFile),'utf8');assert.ok(raw.startsWith(oldWatch));assert.equal((await store.list({kind:'watch'})).items.length,4);});
test('creation append, full correction and workshop artifact retain all versions',async t=>{const {store}=await fixture(t);const first=await store.save(await payload(store,creation('点子','第一句')));const second=await store.save(await payload(store,{...creation('点子','第二句'),id:first.item.id}));assert.equal(second.item.body,'第一句\n\n第二句');const third=await store.save(await payload(store,{...creation('新标题','更正文'),id:first.item.id},{action:'correct'}));assert.equal(third.item.body,'更正文');assert.equal(third.item.history[1].item.body,'第一句\n\n第二句');const artifact={draft:{story:{want:'愿望'}},artifact:{text:'剧本'},island:'story'};const fourth=await store.save(await payload(store,{...creation('新标题',''),id:first.item.id,artifact}));assert.equal(fourth.item.body,'更正文');assert.deepEqual(fourth.item.artifact,artifact);assert.equal(fourth.item.history.length,4);});
test('new content can exceed old UI 128KiB boundary without UI state writes',async t=>{const {root,store}=await fixture(t);const result=await store.save(await payload(store,creation('长原稿','字'.repeat(150000))));assert.equal(result.item.body.length,150000);await assert.rejects(fs.stat(path.join(root,'学习小岛/data/ui-state.json')),e=>e.code==='ENOENT');});
test('large repeated append remains readable after crossing a single-submission limit',async t=>{const {store}=await fixture(t);const first=await store.save(await payload(store,creation('长篇','甲'.repeat(150000))));await store.save(await payload(store,{...creation('长篇','乙'.repeat(150000)),id:first.item.id}));const current=await store.detail(first.item.id);assert.equal(current.item.body.length,300002);assert.equal(current.item.history.length,2);});
test('CAS conflict retains both original files and provided request',async t=>{const {root,store}=await fixture(t);const a=await payload(store,creation('一')),b=await payload(store,creation('二'));await store.save(a);const before=await tree(root);await assert.rejects(store.save(b),e=>e.code==='CONTENT_REVISION_CONFLICT'&&!!e.details.currentRevision);const after=await tree(root);assert.deepEqual(Object.keys(after),Object.keys(before));for(const key of Object.keys(before))assert.equal(after[key].bytes,before[key].bytes);});
test('simultaneous processes serialize and reject stale CAS',async t=>{const {root,store}=await fixture(t);const one=await payload(store,creation('one')),two={...one,submissionId:'save_'+randomUUID(),item:creation('two')};const input1=path.join(root,'input1.json'),input2=path.join(root,'input2.json');await fs.writeFile(input1,JSON.stringify(one));await fs.writeFile(input2,JSON.stringify(two));const cli=fileURLToPath(new URL('./cli.mjs',import.meta.url));const outcomes=await Promise.allSettled([input1,input2].map(file=>run(process.execPath,[cli,'save','--root',root,'--scope','isolated','--input',file])));assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);assert.match(outcomes.find(r=>r.status==='rejected').reason.stderr,/CONTENT_REVISION_CONFLICT/);assert.equal((await store.list({kind:'creation'})).items.length,1);});
test('concurrent identical submissions save exactly once across processes',async t=>{const {root,store}=await fixture(t);const request=await payload(store,watch()),input=path.join(root,'input.json');await fs.writeFile(input,JSON.stringify(request));const cli=fileURLToPath(new URL('./cli.mjs',import.meta.url));const results=await Promise.all([1,2].map(()=>run(process.execPath,[cli,'save','--root',root,'--scope','isolated','--input',input])));const parsed=results.map(r=>JSON.parse(r.stdout));assert.equal(parsed.filter(r=>r.duplicate).length,1);assert.equal((await store.list({kind:'watch'})).items.length,5);});
test('source projections are read-only; old workshop and watch draft are findable',async t=>{const {root}=await fixture(t);const store=new ContentStore({projectRoot:root,scope:'isolated',uiStateReader:async()=>({state:{islandState:{records:[{id:'old-1',island:'story',title:'旧书签',note:'旧原话',report:'practice',workshopDraft:{version:1}}]},lifeState:{drafts:{visual:{version:1}},watch:{post:{title:'观看草稿',note:''}}}}})});const data=await store.bootstrap(),bookmark=data.items.find(i=>i.source.kind==='legacy-bookmark');assert.equal(bookmark.readOnly,true);assert.match(bookmark.resumeUrl,/island=story&place=bookmarks&legacyContent=1&legacyRecord=old-1/);assert.ok(data.items.some(i=>i.source.kind==='legacy-draft'));assert.ok(data.items.some(i=>i.source.kind==='legacy-watch'));await assert.rejects(store.save(await payload(store,{...creation(),id:bookmark.id})),e=>e.code==='CONTENT_READ_ONLY');});
test('malformed source and native files error rather than return empty',async t=>{const {root,store}=await fixture(t);await fs.appendFile(path.join(root,watchFile),'\n<!-- personal-watch:v1 BROKEN -->\n');await assert.rejects(store.bootstrap(),e=>e.code==='CONTENT_CORRUPT');await fs.writeFile(path.join(root,watchFile),oldWatch);const saved=await store.save(await payload(store,creation()));await fs.writeFile(path.join(root,'运行记录/我的内容',saved.item.id+'.json'),'{}');await assert.rejects(store.bootstrap(),e=>e.code==='CONTENT_CORRUPT');});
test('invalid IDs, fields, links and dates cannot write',async t=>{const {root,store}=await fixture(t);const before=await tree(root);for(const item of [{...creation(),id:'../../escape'},{...creation(),date:'2026-02-30'},{...creation(),links:[{url:'javascript:alert(1)'}]},{...creation(),extra:'bad'},{...creation(),artifact:JSON.parse('{"__proto__":{"x":1}}')}])await assert.rejects(store.save(await payload(store,item)));assert.deepEqual(await tree(root),before);await assert.rejects(store.detail('../W001'));});
test('symlink path is rejected without following it',async t=>{const {root,store}=await fixture(t);const external=await fs.mkdtemp(path.join(os.tmpdir(),'xiaomo-content-link-'));t.after(()=>fs.rm(external,{recursive:true,force:true}));await fs.symlink(external,path.join(root,'运行记录/我的内容'),'junction');await assert.rejects(store.bootstrap(),e=>e.code==='LEARNING_UNSAFE_PATH');assert.deepEqual(await fs.readdir(external),[]);});
test('HTTP requires one token and one JSON content type, handles encoded traversal and returns detail',async t=>{const {store}=await fixture(t);const handler=createContentHandler({store,token:'test-token'}),server=http.createServer((req,res)=>{handler(req,res,new URL(req.url,'http://127.0.0.1')).catch(e=>{res.statusCode=500;res.end(e.message);});});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));const base='http://127.0.0.1:'+server.address().port;const bootstrap=await (await fetch(base+'/api/learning/content/bootstrap')).json();assert.equal(bootstrap.token,'test-token');const request={identity:bootstrap.identity,expectedRevision:bootstrap.revision,submissionId:'http_'+randomUUID(),item:watch()};assert.equal((await fetch(base+'/api/learning/content/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)})).status,403);assert.equal((await fetch(base+'/api/learning/content/save',{method:'POST',headers:{'x-content-token':'test-token','content-type':'text/plain'},body:JSON.stringify(request)})).status,415);const success=await fetch(base+'/api/learning/content/save',{method:'POST',headers:{'x-content-token':'test-token','content-type':'application/json'},body:JSON.stringify(request)});assert.equal(success.status,200);const saved=await success.json();assert.equal((await (await fetch(base+'/api/learning/content/items/'+saved.item.id)).json()).item.title,request.item.title);assert.equal((await fetch(base+'/api/learning/content/items/%2e%2e%2f')).status,400);const duplicate=await new Promise((resolve,reject)=>{const req=http.request(base+'/api/learning/content/save',{method:'POST',headers:['Host','127.0.0.1:'+server.address().port,'X-Content-Token','test-token','X-Content-Token','test-token','Content-Type','application/json']},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end(JSON.stringify(request));});assert.equal(duplicate,403);});
